#!/usr/bin/env lua
print (package.path)
---
-- The Lemma REPL
---

-- TODO: more special forms?

require 'exec'

---
-- Execute command line argument or start a REPL
---
local f = ...
local prompt

if not f then
	f = io.input()
	prompt = '> '
end

stdlib()
exec(f, prompt)
