#!/usr/bin/env lua
---
-- The Lemma REPL
---

require 'exec'
LEMMA_VERSION = 0.1

---
-- Execute command line argument or start a REPL
---
local o, f = ...
lemma['*sys-args*'] = Vectorize{...}

function update_prompt()
	prompt = lemma['*ns*']..'> '
end

if o and o:sub(1, 1) ~= '-' then
	f, o = o, nil
end

if o ~= '-nolib' then
	stdlib()
end

if not f or f == '--' then
	f = io.input()
	update_prompt()
	print('Lemma '..LEMMA_VERSION..' (on '.. _VERSION..')')
end

exec(f)
